const bCrypt = require('bcrypt');
module.exports = {
    up: (queryInterface) => {
        return queryInterface.bulkInsert('tables', [
            {
                name: 'Bàn 1',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 2',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 3',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 4',
                status: 'ready',
                numberSeat: 6,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 5',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 6',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 7',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 8',
                status: 'ready',
                numberSeat: 6,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 9',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 10',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 11',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 12',
                status: 'ready',
                numberSeat: 6,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 13',
                status: 'ready',
                numberSeat: 8,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 14',
                status: 'ready',
                numberSeat: 8,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 15',
                status: 'ready',
                numberSeat: 10,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 16',
                status: 'ready',
                numberSeat: 10,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },  {
                name: 'Bàn 1',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 2',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 3',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 4',
                status: 'ready',
                numberSeat: 6,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 5',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Bàn 6',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 7',
                status: 'ready',
                numberSeat: 8,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Bàn 8',
                status: 'ready',
                numberSeat: 10,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
        ], {});
    },

    down: (queryInterface) =>
        queryInterface.bulkDelete('restaurants', null, {})

};
